### ISSUE TITLE
Change the logic of finalizing implementation

### ISSUE THREAD

**Issue by mario7lorenzo** [AY1920S2-CS2103-W15-2/main#182]

**Comment by CornCobs** [comment]
After our online group discussion, we find that finalising is in fact a reasonable behavior as the other proposed behaviors were either unintuitive, or placed a similar restriction eventually anyway.

The proposed options were:
1. Allow unfinalising until the user starts an interview with any interviewee.
2. Have no notion of finalising - updating attributes will maintain the validity of the Model by updating the interviewee's transcripts and the metrics
