### ISSUE TITLE
New interview sessions are created with the finalised flag

### ISSUE THREAD

**Issue by bscrow** [AY1920S2-CS2103-W15-2/main#195]
Currently, new sessions may be set to "finalised" upon creation, which prevents the addition of any attributes or questions to the newly created session.

Steps to replicate:

- start/open an interview session
- set session to finalised using the finalise command
- close session
- start a new session

this is believed to be because while loading a new session, the finalised flag in the previous session is not cleared in the model, causing the new session to "inherit" the finalised flag of the previous session.

**Comment by CornCobs** [comment]
Nice catch! To prevent this bug (and still reduce exposure of the finalised field in ModelManager, I decided to encapsulate all the "resetting" work into a `closeSession` method for Model which does all this internal work.
