### ISSUE TITLE
Update Model and ModelManager

### ISSUE THREAD

**Issue by CornCobs** [AY1920S2-CS2103-W15-2/main#35]
HireLah! has a totally different model from AddressBook, thus Model needs to change.   
Specifically, it needs to:
1. Contain IntervieweeList, AttributeList, QuestionList and Metrics
2. Provide a finalize method which when called, makes AttributeList and QuestionList unmodifiable (Should add a boolean flag to these classes)
3. Contain a mode flag which indicates which mode the app is in, affecting the types of commands that can be given. Modes are Normal mode and interviewing mode

Implementation wise, I think it is ok for ModelManager to simply expose the components, so Commands execute on the components themselves rather than through wrapper methods exposed by Model

**Comment by bscrow** [comment]
Resolved in #57
